#Python 


示例代码展示了三种情况，捕获多种异常、分别捕获异常、捕获所有异常。`finally` 块的代码一定会执行。
```python
def convert_to_int1(s, base):
    try:
        return int(s, base)
    except(ValueError, TypeError):
        return "error"
    
def convert_to_int2(s, base):
    try:
        return int(s, base)
    except ValueError:
        return 'value error'
    except TypeError:
        return 'type error'
    
def convert_to_int3(s, base):
    try: 
        return int(2, base)
    except:
        return 'error'
    finally:
        print("finally...")
```
